### ISSUE TITLE
Missing set up instructions?

### ISSUE THREAD

**Issue by noVerity** [JiriChara/kindergarten#16]
Does this require some specific babel version/set up? The project looked interesting and I wanted to give it a go, but couldn't get it to work. 

With my current set up with webpack/buble/vue both `kindergarten` and `vue-kindergarten` just resolve to objects full of undefined values.

````
{AccessDenied: undefined, ArgumentError: undefined ... }
````

**Comment by JiriChara** [comment]
@noVerity can you please share your webpack config and the way you are trying to import `vue-kindergarten`?

I am using `vue-kindergarten` in https://github.com/JiriChara/chara.vip which is `nuxt.js` application and I did test `vue-kindergarten` in applications that were created using the official `vue-cli/webpack` tool

**Comment by JiriChara** [comment]
You can also have a look on article I wrote: https://medium.com/@JiriChara/role-based-authorization-for-your-vue-js-and-nuxt-js-applications-using-vue-kindergarten-fd483e013ec5#.qee4upbm8 which basically describes all steps that are necessary to integrate `vue-kindergarten`. I am working on better documentation and it should be available soon!

**Comment by noVerity** [comment]
````
{
        ...
        module: {
            rules: [
                {
                    test: /\.js$/,
                    loader: 'buble-loader',
                    exclude: /node_modules/,
                    options: {
                        objectAssign: 'Object.assign'
                    }
                },
                {
                    test: /\.vue$/,
                    loader: 'vue-loader',
                    options: {
                        loaders: {
                            'less': PROD ? ExtractTextPlugin.extract({
                                use: ['css-loader', 'less-loader'],
                                fallback: 'vue-style-loader'
                            }) : 'vue-style-loader!css-loader!less-loader'
                        },
                        buble: {
                            objectAssign: 'Object.assign'
                        }
                    }
                },
                {
                    test: /\.(eot|woff2?|ttf|svg)$/,
                    use: [{
                        loader:'file-loader',
                        options: {
                            name: './fonts/[name].[ext]'
                        }
                    }]
                },
                {
                    test: /\.css/,
                    loader: PROD ? ExtractTextPlugin.extract({
                            fallback: 'style-loader',
                            use: 'css-loader'
                    }) : ['style-loader', 'css-loader']
                }
            ]
        },
        ...
    };
````

In the script files a simple `import { Perimeter } from 'vue-kindergarten'` will just populate Perimeter with `undefined`.

I also get a warning from webpack about the library:

````
WARNING in ./~/kindergarten/lib/Kindergarten.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* <project>/node_modules/kindergarten/lib/Kindergarten.js
    Used by 4 module(s), i. e.
    <project>/node_modules/vue-kindergarten/lib/index.js
* <project>/node_modules/kindergarten/lib/kindergarten.js
    Used by 2 module(s), i. e.
    <project>/node_modules/kindergarten/lib/Kindergarten.js

````

**Comment by JiriChara** [comment]
What OS are you using? I didn't test kindergarten on windows and it seems like there is a issue, because kindergarten exports `Sandbox` class and `sandbox` decorator and since windows in case-insensitive then it might fail. I will look into it later today.

Did you try `vue-cli` to create your application? I have created a short demo: https://www.screencast.com/users/jiri-chara/folders/Default/media/90c2cb87-5818-43ca-ade7-48f6ceb23d27

**Comment by noVerity** [comment]
I am on OS X, I didn't use vue-cli as I was trying to integrate it with an existing set up.

**Comment by JiriChara** [comment]
I have just tested it on OS X and I have the same issue. I will fix it today. Thanks for letting me know!

**Comment by JiriChara** [comment]
@noVerity Fixed in both kindergarten and vue-kindergraten :tada:
