### ISSUE TITLE
Cannot find module "kindergaten/decorators"

### ISSUE THREAD

**Issue by ammichael** [JiriChara/kindergarten#21]
Hi there!

I'm just trying to get started in Kindergarten and I'm having trouble in importing decorators. I'm using v1.5.2 in OSX 10.13, and I'm importing just like in read me:
 ```
import { sandbox }  from 'kindergarten/decorators';
```
The Sandbox class is successfully imported from 'kindergarten' package, but not the decorator - which is exactly what I need 😕

Any help?

Thanks!

Edit:

It works if I import like this:
```
import { sandbox }  from 'kindergarten/lib/decorators';
```

**Comment by JiriChara** [comment]
Hi @ammichael,

thanks for pointing this out! I have updated the README for now, but I will find create a shortcut to import those easier as soon I will find time to do so.
